### PR TITLE
Prepare next production

### PR DESCRIPTION
**Pull request by swertz**
- Corrected muon isolations
- New CSVv2 working points
- Moved to a single config file (as HHAnalysis)
- Moved to 76X
- Use latest JEC
- Add JEC/JER systematics

Anything else (no merging until we're sure)?

### CODE REVIEW

**Comment by blinkseb** [comment]
Great thanks!

I'd prefer to keep two different configuration file. It's much easier to handle when launching on crab than to remember that you have to edit the file before sending. If you want, you can move the command part to a _common_ python file, and call it from the MC and DATA cfg.

**Comment by swertz** [comment]
There is no way to adapt the config on-the-fly for data or MC from GridIn?

**Comment by blinkseb** [comment]
Not currently :(

**Comment by swertz** [comment]
I've updated the PR. In the end I kept two files as before...

Should we think about adding the Top Pt reweighting and the trigger scale factors/efficiencies at this stage or try to include them at the plotting stage? I think it'd be more flexible to have this included later...

**Comment by blinkseb** [comment]
I'm still a bit uncomfortable wrt top pt reweighting. I'm not sure would should apply it ( https://twiki.cern.ch/twiki/bin/view/CMS/TopSystematics#pt_top_Reweighting )

Concerning trigger efficiencies, we have SFs for Double Muons already in the framework, but we need to store them in our tree if we want to use it later. There's nothing for electrons and it has been clearly mentioned that we have to derive our own efficiencies / SFs :(

**Comment by swertz** [comment]
All right, let's keep Pt reweighting on hold, this is something that we can add later if needed...

For the trigger I was thinking of somehow incorporating these results: https://indico.cern.ch/event/487265/contribution/3/attachments/1220074/1783203/Talk_Till_mumu.pdf (where they have MuMu, EE and MuE)
The ID/iso working points they use are different than what we've been doing, but they show a significant discrepancy between data and MC trigger efficiencies. So either we change our selection and ask them for their numbers, or we try to measure trigger efficiencies ourselves... 
Either way these is stuff we can add in the plotting or skimming step, so I think we can move on for now...

**Comment by blinkseb** [comment]
Ah nice, good to keep that in mind so :) I'm merging

**Pull request merged**
