### PR TITLE
First tests

### PR DESCRIPTION
**Pull request by swertz**
Version used for first preliminary tests on "complete" MC & data samples.
- Moved the Z veto from a category to a cut in the TTDilepton category, to avoid writing each event which doesn't have a Z (ie all of them)
- Added possibility to choose from the config file which electron/muonID should be used to define the dileptonCategories
- Added lists of indices for veto and medium ID leptons
- Removed electron Iso cut since it's already applied in the ID (to be checked)
- Updated muon iso cut
- Added list of indices for selected jets (to be discussed: necessary to ask for a minimal DR(j,l) ?)
- Updated things here and there so that everything can be run on 25ns MC/data

### CODE REVIEW

**Comment by blinkseb** [comment]
Testing it :)

**Comment by blinkseb** [comment]
Shouldn't the `NoZTT*Category` categories be removed?

**Comment by swertz** [comment]
It does something different from the Z veto, so I wanted to keep it separately: an event falls in NoZ\* when the seleced leading lepton pair is not in the Z peak, whereas the ZVeto\* categories vetoes any pair of leptons in the Z peak.
But we could also implement it as a cut in the TTDilepton category (the problem with all the events passing the cut is not a problem here since _NoZ_ derives from the _TTDilepton_)... 
I'm not sure yet whether we should veto _any_ other extra lepton, or just the ones consistent with a Z present in the event. I'm also wondering why http://cms.cern.ch/iCMS/analysisadmin/cadi?ancode=TOP-15-003 vetoes e/mu pairs with m_ll < 20GeV since resonances only decay so same flavour leptons (right?)...

**Comment by blinkseb** [comment]
Ok I see, so it's good for me :smile: I'll merge as it is, and we can discuss the remaining open items tomorrow.

**Comment by swertz** [comment]
Thanks!

**Pull request merged**
