### PR TITLE
Episode Two: Revenge of the Maps

### PR DESCRIPTION
**Pull request by swertz**
Addresses #5 , #6, #7, #8  and #10. 
Runs fine on MC (I still have to take a look at what is actually produced to make sure there is no bad surprise there), but I get this on data (=> for now, not for merging):

```
Begin processing the 1st record. Run 254292, Event 352836, LumiSection 1 at 16-Oct-2015 22:36:57.810 CEST
----- Begin Fatal Exception 16-Oct-2015 22:37:12 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 254292 lumi: 1 event: 352836
   [1] Running path 'p'
   [2] Calling event method for module ExTreeMaker/'framework'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::TriggerResults
Looking for module label: TriggerResults
Looking for productInstanceName: 
Looking for process: PAT
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
16-Oct-2015 22:37:12 CEST  Closed file file:///storage/data/cms/store/data/Run2015C/DoubleMuon/MINIAOD/PromptReco-v1/000/254/292/00000/E20B7746-8245-E511-B593-02163E0135AD.root
```

Using the datafile in the example config file. What is going on here?

### CODE REVIEW

**Comment by blinkseb** [comment]
Which input file are you using on data? If it's prompt reco, be sure to correctly change the process name from 'PAT' to 'RECO' using the `process_name` parameter of the `create` function (only on 7.4.12 branch). Otherwise, you can run like:

```
cmsRun config.py process=RECO
```

[1] https://github.com/cp3-llbb/Framework/blob/CMSSW_7_4_12p/python/Framework.py#L41

**Comment by swertz** [comment]
It's prompt reco. Running with process=RECO works (I thought since it was a miniAOD file, PAT would work?)!

But I think something else is wrong: out of 2000 DoubleMuon data events, not one gets selected, and out of 2000 TT MonteCarlo events, only 19 are selected (ie have at least one diLepton pair, whatever IDs).

**Comment by swertz** [comment]
Also, see [Framework 81](https://github.com/cp3-llbb/Framework/issues/81): 3D vectors don't work.

**Comment by blinkseb** [comment]
Yeah they messed up with process name: prompt is 'RECO' while rereco is 'PAT'... GridIn takes that automatically into account.

We maybe also have an issue with the triggers we use, they maybe changed for 2015D and the XML file needs to be updated. I can't check right now but do we also ask for trigger matching in MC? Maybe the list is different on MC and Data ...

**Comment by swertz** [comment]
Trigger matching is implemented as a cut and shouldn not affect the number of selected events by the categories. From https://twiki.cern.ch/twiki/bin/view/CMS/TopTrigger it seems there is a slight difference in the path names between Data and MC: it should be correct in the test config files.

**Comment by swertz** [comment]
Updated to latest working version. Closes #5, #6, #7, #8, #10, and #12.

**Pull request merged**
