### PR TITLE
On the road again!

### PR DESCRIPTION
**Pull request by blinkseb**
Some fixes from #20 for the upcoming production. To be merged only when #20 is empty.

@swertz I gave you push access to my personal fork, so feel free to push fixes to the branch if you want.

### CODE REVIEW

**Comment by swertz** [comment]
Awesome, thank you! :smile:

**Comment by blinkseb** [comment]
@swertz new commit for b-jets eta cut is here: https://github.com/blinkseb/TTAnalysis/commit/1d97b895987366bcbc99f82ed822de909ae75f3f

Is it what you had in mind?

**Comment by swertz** [comment]
Precisely, thanks a lot! :)

**Comment by blinkseb** [comment]
Rebased on top of master. Ready to merge?

**Comment by swertz** [comment]
Looking at the list, I think so!

**Pull request merged**
